### PR TITLE
pull request created

### PR DESCRIPTION
**Pull request by Jushan-Randy-Chen**

### CODE REVIEW

**Comment by emmac4** [comment]
Hi Randy! I think your code looks pretty good, everything seems to be organized pretty well! I just have a few comments: 

- Lines 128-133 are a bit unclear on what you're doing to me. Looking at it, it seems like you're saving states & actions on the last training episode for your trajectory plot, but I think adding a comment to explain this would be helpful, because it's not super clear at first glance. It also might be useful to plot the return of your trajectory as well, so its easier to understand if a good policy has been learned
- Sort of extending on the previous point, it looks like you're using the saved trajectories from those lines to plot your policy, but I'm not sure this is the right way to go about that. From my understanding, to plot the policy you need some discretized list of possible states and then find the actions from your trained policy for each of those states, and then make the contour plot based on that - and the same process for plotting values. (hopefully that explanation makes sense) 
- I don't see that you are decaying epsilon at all in your code, the only place I see epsilon defined is in the 'act' function where you set it to 0. It could be worth it to try setting a larger epsilon in the beginning of training and then decaying to a smaller number later. It might be helpful to set epsilon as an input for your DQN agent. 
- You have an input 'tau' for the DQN_standard class but I don't see you using this value anywhere else in the code
- Don't forget to show results for the policy model using Tanh() activation functions like mentioned in the homework prompt

**Comment by RandyChen233** [comment]
Thanks for the comments! I know what needs to be fixed now. However, I wonder where I should get the discretized list of states to plot the policy?

**Comment by Jushan-Randy-Chen** [comment]
> Hi Randy! I think your code looks pretty good, everything seems to be organized pretty well! I just have a few comments:
> 
> * Lines 128-133 are a bit unclear on what you're doing to me. Looking at it, it seems like you're saving states & actions on the last training episode for your trajectory plot, but I think adding a comment to explain this would be helpful, because it's not super clear at first glance. It also might be useful to plot the return of your trajectory as well, so its easier to understand if a good policy has been learned
> * Sort of extending on the previous point, it looks like you're using the saved trajectories from those lines to plot your policy, but I'm not sure this is the right way to go about that. From my understanding, to plot the policy you need some discretized list of possible states and then find the actions from your trained policy for each of those states, and then make the contour plot based on that - and the same process for plotting values. (hopefully that explanation makes sense)
> * I don't see that you are decaying epsilon at all in your code, the only place I see epsilon defined is in the 'act' function where you set it to 0. It could be worth it to try setting a larger epsilon in the beginning of training and then decaying to a smaller number later. It might be helpful to set epsilon as an input for your DQN agent.
> * You have an input 'tau' for the DQN_standard class but I don't see you using this value anywhere else in the code
> * Don't forget to show results for the policy model using Tanh() activation functions like mentioned in the homework prompt

Thanks for the comments! I know what needs to be fixed now. However, I wonder where I should get the discretized list of states to plot the policy?

**Comment by emmac4** [comment]
> 

We know the bounds for the state space from looking at the discrete_pendulum environment, so there is a max/min thetadot and theta will be between -pi and pi, so what I did was just create two arrays using numpy.linspace of a number of values between these bounds; then you can get the state inputs  using combinations from these two lists. There are probably other ways to do this, but for me this was the most straightforward way I could think of.

**Comment by Jushan-Randy-Chen** [comment]
> > 
> 
> We know the bounds for the state space from looking at the discrete_pendulum environment, so there is a max/min thetadot and theta will be between -pi and pi, so what I did was just create two arrays using numpy.linspace of a number of values between these bounds; then you can get the state inputs using combinations from these two lists. There are probably other ways to do this, but for me this was the most straightforward way I could think of.

Thanks, I just fixed these issues!

**Pull request closed without merging**
